### ISSUE TITLE
Lock in marketing text

### ISSUE THREAD

**Issue by futuresoup** [climate-tech-handbook/climate-tech-handbook#153]
## Fill below:

- [ ] Nav buttons
- [ ] Hero slogan
- [ ] Footer content
- [ ] Card titles & sentences
- [ ] Site title (add "The")

---

#### Version A: [current website tagline](https://www.climatetechhandbook.com/)

```
We are here to help you answer the most important question in the world:
How am I going to make a difference?
```

Button says: **`Find out`**

(This version depends on having a section with two font sizes, smaller for sentence 1 and larger for sentence 2.)

---

#### Version B: 

We’re building the most accessible and accurate climate tech resource on the planet.

Button says: **`Show me`**

---

### Top row navigation

* `The Climate Tech Handbook`  (Has "The" in it)
* `Climate Job Seekers`
* `Climate Startups`
* `About Us`
* `News`

### Footer

- [ ] Remove `Technologies` under **Resources**
- [ ] Under solutions, change text to `List of climate solutions`

### Card Titles and Paragraph

**`Climate Job Seekers`**
```
Becoming a climate expert feels daunting.

But it's easier than you think.

If you don't currently work in tech, you also have options.

```

Button says: **`We can help`**

---

**`Climate Startups`**
```
The climate tech landscape is changing rapidly.

Founders, investors, philanthropists, and government funders - all have a responsibility to spend money wisely.

Our future depends on it.

Get the best information possible on what's working, and what to avoid.
```

Button says **`Show me`**

**Comment by futuresoup** [comment]
@UlianaBil please see above for updating Figma.

**Comment by UlianaBil** [comment]
@futuresoup There is one of the pages for you to see all changes you requested.

- Top navbar contains titles that are too long. I made them shorter
- Instead of buttons "Show me", "We can help" - "Learn more", more user friendly.
- Card descriptions- I added a little more text, we need a little bit longer paragraph. ( will be changed in the final version)

[Homepage Layout #1.pdf](https://github.com/climate-tech-handbook/climate-tech-handbook/files/11788417/Homepage.Layout.1.pdf)
