### ISSUE TITLE
mkdocs 1.4.3 and markdown 3.4.3 dependancy conflict

### ISSUE THREAD

**Issue by benj1r** [climate-tech-handbook/climate-tech-handbook#172]
Attempting to install both **mkdocs** and **markdown** from the `requirements.txt` file yields:

```
ERROR: Cannot install -r requirements.txt (line 12) and Markdown==3.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested Markdown==3.4
    mkdocs 1.4.3 depends on markdown<3.4 and >=3.2.1
```

**Comment by futuresoup** [comment]
Darn... @justBanks do you have a fix?

@benj1r you should be able to run `pip install mkdocs-material` because that's all it is, a [Material for MKDocs](https://github.com/squidfunk/mkdocs-material) instance.

@benj1r we are soon migrating to docusaurus [via this repo](https://github.com/climate-tech-handbook/docusaurus-test) - if you want to wait until that's complete?
