### ISSUE TITLE
Social Icons Relative Image Src

### ISSUE THREAD

**Issue by djwar42** [climate-tech-handbook/climate-tech-handbook#474]
When viewing a sub page, the social icons appear to be missing, they seem to be using a relative img src

<img width="1435" alt="image" src="https://github.com/climate-tech-handbook/climate-tech-handbook/assets/152340915/680a2d60-9f9c-4fb8-ae41-8d029728bc25">

**Comment by futuresoup** [comment]
@djwar42 - thank you for filing this! Yes it's been annoying me and only shows up some of the time, not all the time!

I'm so glad you figured out the problem. And thank you @MyBaBB for volunteering to tackle it.

@djwar42 are there other issues you're noticing that you might find appealing to contribute toward?

**Comment by MyBaBB** [comment]
I was looking around, I figure I could figure it out,   I see a problem but
I haven't corrected it yet,   I am trying to deploy my version first,
because it only shows up after its deployed,
I have to learn Netlify,  I normally use github pages or render,   But I
figure netifly would be easier since is already set up,  I might just have
to change a few things.
Netlify Doesn't work all the way around,,  It wont even let me create an
account.  Is there some way to test it  without turning it in so I can see
that it works ?   Maybe you guys have a method,

**Comment by djwar42** [comment]
Just a note on the images, they appear correctly if you navigate from the home page to a sub page, the issue only occurs if you do a hard refresh on a sub page.

Thanks!

**Comment by MyBaBB** [comment]
I  made a build folder and put it on Render.com and it works fine on all browsers.  
We can try it on Netlify now to test ,  Thats about all I can do until we see if it works.
I cant get the old develop  branch to work its from 9 months ago and the update might have messed it up  from 3 months ago.   So that needs work.  unless I am just confused about it .  
I think it is the way Netlify is interpreting something, it probably has the image confused.  Try it now after I moved them around and changed the name by adding a 2 to the end. That little trick by changing the name works often for me on other things. I just moved them because I know that that other path is working fine for the image above them.   Test to see. while we figure out the deploy branch in the near future.

**Comment by MyBaBB** [comment]
##ok, I repaired the develop branch and tested it ,  its is on there and it is working.   You can go to the develop branch and see.  The develop branch is up to Date now.  It was old and I could not get it to install npm i on my machine because it was looking for the new version.   Everything looks good with  the approval you can  merge this and close it.

**Comment by MyBaBB** [comment]
# 474 Social Icons in Footer

## CSS Changes

I made adjustments to the `.footer-logo-social-links` class:
- Added `width: -moz-fit-content;`
- above the  `width: fit-content;`

## Image Relocation

I encountered an issue with the file path for one of the images, causing a glitch. To resolve this, I relocated the problematic image to the same folder as the working image. This change involved grouping all images within the relevant `div`.

## Image Naming Convention

To address potential issues with image loading, especially after modifications, I adopted a naming convention where I appended a "2" to the names of the affected images. This approach helps differentiate between original and modified versions, encouraging the system to load the correct image.

## Additional Notes

Upon further investigation, I found that Netlify's default configuration includes a development branch, which streamlined the deployment process. After cleaning up my local deploy branch and removing unnecessary notes, everything appears to be in order for submission. This experience highlights the importance of thorough preparation and cleanup before finalizing project submissions.
